apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: oficina
spec:
  selector:
    app: email
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: http
      port: 8025
      targetPort: http
