apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-app
  namespace: oficina
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://banco:5432/oficina
  SPRING_MAIL_HOST: email
  TZ: UTC
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
  SERVER_TOMCAT_ACCESSLOG_DIRECTORY: /dev
  SERVER_TOMCAT_ACCESSLOG_PREFIX: stdout
  SERVER_TOMCAT_ACCESSLOG_SUFFIX: ""
  SERVER_TOMCAT_ACCESSLOG_ROTATE: "false"
  SERVER_TOMCAT_ACCESSLOG_BUFFERED: "false"
  SERVER_TOMCAT_ACCESSLOG_PATTERN: "%t %m %U %s %F ms"
